### ISSUE TITLE
Update inmanta quickstart

### ISSUE THREAD

**Issue by kazaamjt** [inmanta/quickstart-docker#1]
The current quickstart should be streamlined and updated.
Initial tests using docker look good and would simplify using the quickstart.

**Comment by arnaudsjs** [comment]
Remarks: 

1) Selinux blocks mount of test-project directory on Fedora and Centos7. Any need to store quickstart project in the quicktstart-docker repository (duplication)
2) Why install the python3-inmanta python3-inmanta-agent packages on agent containers? autostarted agents are used, right?
3) Name of containers should be pinned (fedora: quickstart-docker_inmanta-server_1 <=> centos: quickstartdocker_inmanta-server_1). This way the docker exec command fails
4) Build via the dashboard do not work since there is no main.cf file on https://github.com/inmanta/quickstart
5) We should indicate in the last step of the README.md that it also triggers the deployment
6) Deployment quickstart doesn't work due to the fact that the SSH connectivity doesn't work

[root@993e7d7d9db0 test-project]# ssh root@172.28.0.4
The authenticity of host '172.28.0.4 (172.28.0.4)' can't be established.
ECDSA key fingerprint is SHA256:m+MpcE4x7KzjaCMFKl8rkqrfKyvNFI7LbRK7LdIPjAo.
ECDSA key fingerprint is MD5:1a:7d:ce:53:57:b2:af:57:16:09:e0:f1:6a:e8:6e:5e.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '172.28.0.4' (ECDSA) to the list of known hosts.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0664 for '/root/.ssh/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.

7) Port to the drupal site is not mapped to host. So there is no elegant way to view the end result.

**Comment by kazaamjt** [comment]
3: Done

**Comment by kazaamjt** [comment]
3: done

**Comment by kazaamjt** [comment]
@arnaudsjs could you double check everything is resolved??
